### ISSUE TITLE
Comments doesn't work for other Config objects inside a Config

### ISSUE THREAD

**Issue by bibo38** [Cube-Space/Yamler#14]
```java
import java.io.File;

import net.cubespace.Yamler.Config.Comment;
import net.cubespace.Yamler.Config.Config;
import net.cubespace.Yamler.Config.InvalidConfigurationException;

public class TestConfig extends Config
{
	public class InnerConfig extends Config {
		@Comment("This is another important field")
		public int x = 0;
	}

	@Comment("A field")
	public int a = 7;
	
	public InnerConfig inner = new InnerConfig();

	public TestConfig()
	{
		CONFIG_FILE = new File("test.yml");
	}

	public static void main(String args[])
	{
		Config test = new TestConfig();
		try
		{
			test.init();
		} catch (InvalidConfigurationException e)
		{
			e.printStackTrace();
		}
	}
}
```

This example produces the following test.yml:
```yaml
# A field
a: 7
inner:
  x: 0
```

But the comment of the inner config field won't get printed to the file, as expected:
```yaml
# A field
a: 7
inner:
  # This is another important field
  x: 0
```
