### ISSUE TITLE
Saving an Array of Config objects results in a wrong configuration

### ISSUE THREAD

**Issue by bibo38** [Cube-Space/Yamler#17]
```java
import java.io.File;

import net.cubespace.Yamler.Config.Config;
import net.cubespace.Yamler.Config.InvalidConfigurationException;

public class TestConfig extends Config
{
	public class InnerConfig extends Config
	{
		public int x = 7;
	}
	
    public InnerConfig configs[] = { new InnerConfig(), 
    		new InnerConfig(),
    		new InnerConfig()
    		};

    public TestConfig()
    {
        CONFIG_FILE = new File("test.yml");
    }

    public static void main(String args[])
    {
        TestConfig test = new TestConfig();
        try
        {
            test.init();
        } catch (InvalidConfigurationException e)
        {
            e.printStackTrace();
        }
    }
}
```

This creates the following test.yml, which is wrong and cannot be loaded again:
```yaml
configs:
- !!TestConfig$InnerConfig
  x: 7
- !!TestConfig$InnerConfig
  x: 7
- !!TestConfig$InnerConfig
  x: 7
```
