### ISSUE TITLE
Frage zu API

### ISSUE THREAD

**Issue by Kraeutergarten** [Cube-Space/Yamler#2]
Hallo,
ist es irgendwie möglich eine ArrayList mit dem Objekt "Channel" abzuspeichern ohne diese "Classpfad Angaben" abzuspeichern ?
Die Classe Channel enthält 
private String name;
private String shortcut;
private String prefix;
private ChatColor color;

So siehts derzeit aus:

```
channels:
- !!at.Nosxxx.Chat.Channel.Channel
  color: WHITE
  name: default
  prefix: '[default]'
  shortcut: d
```

So hätte ich es gerne:

```
channels:
  - color: WHITE
    name: default
    prefix: '[default]'
    shortcut: d
```

Ist das irgendwie möglich ?
